name = "backend"
main = "src/index.ts"
compatibility_date = "2025-07-24"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza185REt3ZFVNUFBrc0dtYmtTOWNwZW8iLCJhcGlfa2V5IjoiMDFLMFlHNjRFWlBXWkY5MzFNSzlITUc5OUgiLCJ0ZW5hbnRfaWQiOiJhNDkzMzAzMDdmYWEzMzg1MTEzMmU5OTQ1NzkxMDNlYTkyMWE5ZGE5NmVlYzhjNjg2ZDg4YTFhNGFjMmM5ZGFmIiwiaW50ZXJuYWxfc2VjcmV0IjoiMDUwN2MzNTQtZTVlZC00NDUzLWIzNjQtYWE0ZDgwNTA2ZjMxIn0.sHpNHeHY4bS0FDzMCNV5d9u5SABq8tqa9X_RTHWwOco"
JWT_SECRET = "asasas"